### ISSUE TITLE
Receiving endpoint doesn't handle message from sending enpoint with NServiceBus.Newtonsoft.Json as serializer

### ISSUE THREAD

**Issue by JSCProjects** [NServiceBusExtensions/NServiceBus.Json#74]
I'm getting this error when a sending endpoint uses NServiceBus.Newtonsoft.Json as serializer.
```
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message d0349047-1d73-460e-9812-ab4b009d0c50
 ---> System.Text.Json.JsonException: '0xEF' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0xEF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadValueCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadValueCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at JsonMessageSerializer.Deserialize(Byte[] buffer, Type type) in C:\projects\nservicebus-json\src\NServiceBus.Json\JsonMessageSerializer.cs:line 60
   at JsonMessageSerializer.Deserialize(Stream stream, IList`1 messageTypes) in C:\projects\nservicebus-json\src\NServiceBus.Json\JsonMessageSerializer.cs:line 49
   at NServiceBus.DeserializeMessageConnector.Extract(IncomingMessage physicalMessage)
   at NServiceBus.DeserializeMessageConnector.ExtractWithExceptionHandling(IncomingMessage message)
   --- End of inner exception stack trace ---
   at NServiceBus.DeserializeMessageConnector.ExtractWithExceptionHandling(IncomingMessage message)
   at NServiceBus.DeserializeMessageConnector.Invoke(IIncomingPhysicalMessageContext context, Func`2 stage)
   at ReceivePerformanceDiagnosticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.Transport.AzureServiceBus.TransactionScopeSuppressBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`1 next)
   at NServiceBus.InvokeAuditPipelineBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.TransportReceiveToPhysicalMessageConnector.Invoke(ITransportReceiveContext context, Func`2 next)
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.InnerProcessMessage(Task`1 receiveTask)
```

**Comment by JSCProjects** [comment]
I've created a [pull-request](https://github.com/NServiceBusExtensions/NServiceBus.Json/pull/75) to fix this behaviour

**Comment by SimonCropp** [comment]
seems a leading bom in json is not allowed as per the json spec https://jimmybogard.com/the-curious-case-of-the-json-bom/. link also contains a workaround

perhaps raise it as a bug in the NSB peeps?

**Comment by JSCProjects** [comment]
Jimmy also created a pull-request to fix this sending behavior in [NServiceBus.Newtonsoft.Json](https://github.com/Particular/NServiceBus.Newtonsoft.Json/pull/54), but then I have to change all the sending/publishing endpoints(not all in my control) who still don't use the [Encoding](https://docs.particular.net/nservicebus/serialization/json#customization-customizing-encoding) fix.

I know it's [forbidden](https://tools.ietf.org/html/rfc8259#section-8.1) to use BOM inside a json, but my [pull-request](https://github.com/NServiceBusExtensions/NServiceBus.Json/pull/75) could get more adoption to use this package.

I didn't find a workaround for the reading part in jimmy's blog.

**Comment by SimonCropp** [comment]
fair enough. given this is a pay for use library (https://github.com/NServiceBusExtensions/Home/#licensingpatron-faq) if you intend to become a sponsor then i will merge the PR. if you dont intend on using the library, then i am think it is better to leave as is.

sound reasonable?

**Comment by JSCProjects** [comment]
Ok understand it's not in proportion with a NServiceBus license and therefore my client isn't willing to become a sponsor. They decided to use NServiceBus.Newtonsoft.Json and wait for official support from Particular. Sorry keep up the good work!

**Comment by SimonCropp** [comment]
ok sounds good.
